project_id = "sstxifqsickevprpuhap"

[functions.sync-manychat]
verify_jwt = false

[functions.stripe-checkout]
verify_jwt = false

[functions.paypal-checkout]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = false

[functions.shippo-webhook]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
