project_id = "sstxifqsickevprpuhap"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.check-abandoned-carts]
    verify_jwt = false
  [functions.paypal-checkout]
    verify_jwt = false
  [functions.paypal-webhook]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = false
  [functions.shippo-webhook]
    verify_jwt = false
  [functions.stripe-checkout]
    verify_jwt = false
  [functions.stripe-webhook]
    verify_jwt = false
  [functions.sync-manychat]
    verify_jwt = false
